version: 2.1
jobs:
  create_and_deploy_front_end:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: |
          aws cloudformation deploy \
            --template-file instances/bucket.yml \
            --stack-name cicdpromotepromotionbucket \
            --parameter-overrides S3Name=promotepromotionbucket
      - run: mkdir webcontent
      - run: aws s3 sync s3://udacitycicdwebcontent webcontent
      - run: sed -i 's/development/production/g' webcontent/index.html
      - run: aws s3 sync ./webcontent s3://promotepromotionbucket --delete

  promote_to_production:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: |
          aws cloudformation deploy \
            --template-file instances/cloudformation.yml \
            --stack-name cloudfront \
            --parameter-overrides PipelineID=cicdpromotepromotionbucket

workflows:
  default:
    jobs:
      - create_and_deploy_front_end:
          context:
            - aws_vars
      - promote_to_production:
          context:
            - aws_vars
          requires:
            - create_and_deploy_front_end
